// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djciumoyoyrhbgkysyvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqY2l1bW95b3lyaGJna3lzeXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODUxNDEsImV4cCI6MjA1OTM2MTE0MX0.cZceBakOM4DCbd9CETCd1_0mGTNq9cDZ8TrCLMGghvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);